### ISSUE TITLE
[REBL] [Trove iX] Turning Car Off (Pressing 'X'), Makes High Pitched Engine Noise

### ISSUE THREAD

**Issue by eandr127** [Ambaen/Ambaen#2]
Whenever turning off car, the engine sound plays and maximum pitch.  This is quite unrealistic.  (Because normal cars that are turned of don't make high pitched engine noises)  It is also somewhat annoying.  This is probably due to the engine being at its maximum speed, which is zero, because the car is off.  A solution could be to disable the script that handles engine sounds.

**Comment by eandr127** [comment]
Fixed as of https://github.com/Ambaen/Ambaen/tree/v1.1.0

**Comment by biscuitseed** [comment]
Turning sound pitch to "0" will fix this, although X is not included in my cars as of v1.1.0 (may re-add in v1.1.1)

**Comment by eandr127** [comment]
Sorry I accidentally closed the issue

**Comment by biscuitseed** [comment]
Okay. I'll see if I can get X working how it's supposed to as well (Putting car into a "handbrake mode" so it won't roll down hills when stopped), and now the high pitched noise is sorted out.

**Comment by eandr127** [comment]
I thought this was #4 not #2 so it was supposed to be closed but I will leave it open

**Comment by biscuitseed** [comment]
I will close it as the bug is fixed now.

**Comment by eandr127** [comment]
OK in 1.1.2?

**Comment by biscuitseed** [comment]
Yes. Working on reimplementing X system now and releasing 1.1.2, can't give an estimated time though.

**Comment by eandr127** [comment]
Have you uploaded the new models?

**Comment by eandr127** [comment]
I updated your release post

**Comment by biscuitseed** [comment]
Fixed,  closing

**Comment by eandr127** [comment]
Why are you reopening a closed issue when you said closing?
