### ISSUE TITLE
[Ambaen] [Physics / lag issue] Turning & lights lag after ~5 minutes of driving around

### ISSUE THREAD

**Issue by caelan-douglas** [Ambaen/Ambaen#4]
Drive around in a map for around 5 minutes, you will start to notice short lag spikes when turning.  This has something to do with ToggleLights, R-Chassis never used to do this.  Causes: Possibly broken scripts in ToggleLights. Possible Solutions: Fix any broken scripts (found through View > Output)
- biscuitseed

**Comment by eandr127** [comment]
Thank you, I'll look into it.  Also you don't have to include the '[', ']', and "||".  And if possible the title should include the issue tags (which would have [] brackets).  It isn't that important though.

**Comment by biscuitseed** [comment]
Output log (entering vehicle) incase this helps. DisableAll is still valid, I will try removing it and see if that does anything:
//OUTPUT//
11:45:45.941 - Lights is not a valid member of ScreenGui
11:45:45.942 - Script 'Workspace.2015 Ambaen Varis iX.DriveSeat.DisableAll.Control', Line 9
11:45:45.943 - Stack End

**Comment by eandr127** [comment]
OK.  Also can you go to https://github.com/Ambaen and accept my invite?

**Comment by eandr127** [comment]
I can't work on it until later tonight though, sorry.

**Comment by eandr127** [comment]
Also don't add the confirmed label unless at least one other person can confirm it

**Comment by eandr127** [comment]
Does it affect 2016 models?

**Comment by biscuitseed** [comment]
Yes, it affects all models.

**Comment by biscuitseed** [comment]
Also seems to happen when pressing S and W

**Comment by biscuitseed** [comment]
Also, the lag spikes last longer the longer you are in the car

**Comment by biscuitseed** [comment]
Adornee seems to freak out with count parameter and activity - may be the problem http://prntscr.com/66ffnq

**Comment by biscuitseed** [comment]
whoops

**Comment by biscuitseed** [comment]
I have found the source of the bug, has something to do with reverse (S) lights.

**Comment by biscuitseed** [comment]
Bug fixed, closing, adding models now.
